#This file is in ANSI encoding! If it doesn't work with your langauge, try switching to another encoding

botConfig:
  TOKEN: 
  IP: 
  PORT:
  STARTCOMMAND: ./start.sh
  COMMANDPREFIX: "!!" #default: !!


langSettings: #Customise for your langauge (default: HU_hu)
  general:
    botOnline: "Bot elérhetõ" #Message to send when bot goes online (python console)
  statusCommand:
    onRun: "Információ lekérdezése" #Message to send on running the command
    online: "Igen" #Messsge to send if server online
    offline: "nem" #Message to send if server offline
    embedTitle: "Szerver info:" 
    playersOnline: "Játékosok online:" 
  startCommand:
    onRun: "Szerver ellenõrzése..."
    serverAlreadyRunning: "A szerver már fut!"
    startingServer: "Szerver indítása"
    serverOnline: "Szerver online" #Message to send when the server is online
