#WARNING!!! This file is in ANSI encoding!

botConfig:
  TOKEN: OTk3OTEwODkyNzIzMzA2NTY2.GN6XH1.e1-Pz5fVUkfd5g52RoDd5cMcewVqDK43PBBKYc
  IP: 178.48.150.51
  PORT: 25565
  STARTCOMMAND: ./start.sh
  COMMANDPREFIX: "!!" #default: !!
embedConfig:
  #Not finished

langSettings: #Customise for your langauge (default: HU_hu)
  general:
    botOnline: "Bot elérhetõ" #Message to send when bot goes online (python console)
  statusCommand:
    onRun: "Információ lekérdezése" #Message to send on running the command
    online: "Igen" #Messsge to send if server online
    offline: "nem" #Message to send if server offline
    embedTitle: "Szerver info:" 
    playersOnline: "Játékosok online:" 
  startCommand:
    onRun: "Szerver ellenõrzése..."
    serverAlreadyRunning: "A szerver már fut!"
    startingServer: "Szerver indítása"
    serverOnline: "Szerver online" #Message to send when the server is online
